version: "3"

services:
  web:
    build: 
      context: .
      args:
        mix_env: dev
    image: "bullion:0.1.0.dev"
    ports:
      - "4000:4000"
    environment:
      - PORT=4001
      - DATABASE_URL=postgresql://postgres:postgres@db/bullion
  db:
    image: "postgres:12"
    container_name: "bullion-db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bullion
    expose:
      - "5432"
